# Dependencies
markdown:         redcarpet
highlighter:      pygments




# Setup
title:            pra-kri
tagline:          'Prabesh K'
description:      'Thoughts + essays + code on decision-making, uncertainty, and related areas.'
url:              https://pra-kri.github.io
baseurl:          /pra-kri.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
